#!/bin/sh
# chkconfig: 2345 55 99
# description:ignore
. /etc/init.d/functions

httpd="/application/apache/bin/apachectl"
PROG="apache"


USAGE(){
	echo "Usage $0 {start|stop|restart|reload}"
	exit 0
}


start(){
	if [ ! -f /var/lock/subsys/$PROG ] 
	 then
		$httpd start &>/dev/null
		touch /var/lock/subsys/$PROG
		action "httpd is Started"  /bin/true			
	else
		echo "httpd already running"
	fi
	
	return $RETVAL
}

stop(){
	if [ -f /var/lock/subsys/$PROG ]
	 then
		$httpd stop &>/dev/null
		rm -f /var/lock/subsys/$PROG
		action "httpd is Stopped"  /bin/true
	 else
		echo "httpd not running"	
		exit
	fi
	return $RETVAL
}



reload(){
	if [ -f /var/lock/subsys/$PROG ]
		 then
			$httpd graceful
			action "httpd graceful is OK"
		 else
			echo "httpd not running"
		fi
	return $RETVAL

}


case `echo $*|tr "[A-Z]" "[a-z]"` in
  start)
	start
	;;
  stop)
        stop
        ;;
  restart)
        stop
	start
        ;;
  reload)
        reload
	;;
       *)
	USAGE
esac
  
exit $RETVAL

